#!/bin/bash
path="$PYFILE"

if [ -z "$PYFILE" ]; then
    echo "Env. variable was not set."
    exit 1
fi

if [ ! -f "$PYFILE" ]; then
    echo "PYFILE was not found."
    exit 1
fi

python3 "$PYFILE"
