#!/bin/bash
path="$PYFILE"

if [ -z "$PYFILE" ]; then
    echo "The environment variable was not set."
    exit 1
fi

if [ ! -f "$PYFILE" ]; then
    echo "The file expected to be stored in PYFILE was not found."
    exit 1
fi

python3 "$PYFILE"
